apiVersion: apps/v1
kind: Deployment
metadata:
  name: substrate
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: substrate
  replicas: 1
  template:
    metadata:
      labels:
        app: substrate
    spec:
      containers:
        - name: substrate
          image: parity/substrate:2.0.0-31c633c47
          imagePullPolicy: Always
          args: ["--dev", "--ws-external", "--rpc-external"]
          ports:
          - containerPort: 30333
          - containerPort: 9933
          - containerPort: 9944
---
apiVersion: v1
kind: Service
metadata:
  name: api-endpoint
spec:
  selector:
    app: substrate
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 30333
    targetPort: 30333
    name: ep1
  - protocol: TCP
    port: 9933
    targetPort: 9933
    name: ep2
  - protocol: TCP
    port: 9944
    targetPort: 9944
    name: ep3
