apiVersion: v1
kind: Service
metadata:
  name: api-endpoint
spec:
  selector:
    app: substrate
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 30333
    targetPort: 30333
    name: ep1
  - protocol: TCP
    port: 9933
    targetPort: 9933
    name: ep2
  - protocol: TCP
    port: 9944
    targetPort: 9944
    name: ep3
